extends GutTest
# The baked car silhouettes (scripts/car_silhouettes.gd, generated by
# tools/bake_car_silhouettes.gd) and the CONTRACT the overworld CAR pin draws against.
#
# NOTHING HERE PINS A SHAPE. Which car is long and low, how many points its roofline needs
# and how big its wheels are all come from tunable authored values (`wheelbase`,
# `wheel_radius`, the .glb itself) and from the tracer's resolution, so asserting any of them
# would pin a moving number. What must hold for ANY bake is asserted instead:
#
#   * every baked key is a model the catalogue actually carries (a rename or a removal makes
#     the data stale, and a stale entry draws the WRONG car — worse than the fallback);
#   * every outline is a closed, simple (non-self-crossing) loop with real area, because
#     `Geometry2D.decompose_polygon_in_convex` and `is_point_in_polygon` both assume that;
#   * every outline lives in the pin glyph's unit box, which is the space `_draw_glyph`'s
#     `draw_set_transform` scales by `icon_px`;
#   * the convex pieces really are convex, since `draw_colored_polygon` wants them so;
#   * an UNKNOWN model yields nothing, which is the cue the pin painter falls back on.


func _all() -> Dictionary:
	return CarSilhouettes.SILHOUETTES


func test_keys_are_catalogue_models() -> void:
	var ids := {}
	for spec: Dictionary in CarLibrary.all():
		ids[String(spec.get("id", ""))] = true
	for id: String in _all().keys():
		assert_true(ids.has(id),
				"baked silhouette '%s' is not a CarLibrary model — rebake with tools/bake_car_silhouettes.gd" % id)


func test_outlines_are_simple_closed_loops() -> void:
	for id: String in _all().keys():
		var poly := CarSilhouettes.outline(id)
		assert_gt(poly.size(), 2, "%s: an outline needs at least 3 points" % id)
		# Closed by convention (implicit last->first edge), so no duplicated endpoint, and no
		# duplicated consecutive point anywhere: a zero-length edge breaks triangulation.
		var n := poly.size()
		for i in n:
			assert_false(poly[i].is_equal_approx(poly[(i + 1) % n]),
					"%s: duplicate consecutive point at %d" % [id, i])
		assert_gt(absf(_signed_area(poly)), 0.0, "%s: outline encloses no area" % id)
		var crossing := _first_crossing(poly)
		assert_eq(crossing, "", "%s: outline is self-intersecting (%s)" % [id, crossing])


func test_outlines_share_one_winding() -> void:
	# The baker normalises every outline to a POSITIVE signed area (clockwise on screen, since
	# the glyph box has y pointing down). The convex decomposition and any future stroke/offset
	# pass rely on all of them agreeing, so a mixed bake must fail loudly rather than draw one
	# car inside out.
	for id: String in _all().keys():
		assert_gt(_signed_area(CarSilhouettes.outline(id)), 0.0, "%s: outline winding is flipped" % id)


func test_outlines_sit_in_the_glyph_unit_box() -> void:
	for id: String in _all().keys():
		for p in CarSilhouettes.outline(id):
			assert_between(p.x, -1.0, 1.0, "%s: x outside the unit box" % id)
			assert_between(p.y, -1.0, 1.0, "%s: y outside the unit box" % id)


func test_wheels_are_a_pair_inside_the_outline_bounds() -> void:
	for id: String in _all().keys():
		var hubs := CarSilhouettes.wheels(id)
		assert_eq(hubs.size(), 2, "%s: a side profile shows exactly two wheels" % id)
		var r := CarSilhouettes.wheel_radius(id)
		assert_gt(r, 0.0, "%s: wheel radius must be positive" % id)
		# The wheels were stamped INTO the mask before tracing, so their discs cannot fall
		# outside the shape's own bounds (a floating or sunken wheel is the classic mistake).
		var bounds := _bounds(CarSilhouettes.outline(id))
		for i in hubs.size():
			assert_true(bounds.grow(r * 0.5).has_point(hubs[i]),
					"%s: wheel %d sits outside the silhouette" % [id, i])
		# Front and rear, not two wheels in the same place.
		assert_gt(absf(hubs[0].x - hubs[1].x), r, "%s: the two wheels are not separated" % id)


func test_convex_pieces_are_convex_and_cached() -> void:
	for id: String in _all().keys():
		var pieces := CarSilhouettes.convex_pieces(id)
		assert_false(pieces.is_empty(), "%s: decomposed into no pieces" % id)
		for piece: PackedVector2Array in pieces:
			assert_gt(piece.size(), 2, "%s: a convex piece needs 3 points" % id)
			assert_true(_is_convex(piece), "%s: a piece came back concave" % id)
		# Cached by identity, so a repainting minimap allocates nothing per frame.
		assert_true(CarSilhouettes.convex_pieces(id) == pieces,
				"%s: convex pieces should be cached, not rebuilt" % id)


func test_unknown_model_yields_the_fallback_cue() -> void:
	# A car added before someone reruns the baker, a procedural-body car, and the "" that every
	# non-CAR pin passes. All three must come back EMPTY so the painter draws its generic car
	# rather than nothing at all.
	for id in ["", "__no_such_model__", "MX5"]:
		assert_eq(CarSilhouettes.outline(id).size(), 0, "'%s' should have no outline" % id)
		assert_eq(CarSilhouettes.wheels(id).size(), 0, "'%s' should have no wheels" % id)
		assert_eq(CarSilhouettes.wheel_radius(id), 0.0, "'%s' should have no wheel radius" % id)
		assert_true(CarSilhouettes.convex_pieces(id).is_empty(), "'%s' should have no pieces" % id)
		assert_false(CarSilhouettes.has(id), "'%s' should not report as baked" % id)


func test_every_baked_model_reports_present() -> void:
	for id: String in _all().keys():
		assert_true(CarSilhouettes.has(id), "%s: baked but reports absent" % id)


func test_outline_rasterises_as_a_polygon_icon() -> void:
	# The outline is the single-polygon form PolygonIcon takes, and the pins are drawn at map
	# sizes as small as a dozen pixels; a shape that rasterises to nothing would be an
	# invisible pin. One model is enough — this checks the RASTERISER contract, not the shape.
	var id := String(_all().keys()[0])
	var tex := PolygonIcon.texture("test_car_%s" % id, _scaled(CarSilhouettes.outline(id), 24.0),
			Color.WHITE)
	assert_not_null(tex, "a silhouette should rasterise to a texture")
	assert_gt(tex.get_width(), 0, "rasterised silhouette has no width")
	assert_gt(tex.get_height(), 0, "rasterised silhouette has no height")


# ==========================================================================================
# Helpers
# ==========================================================================================

func _scaled(poly: PackedVector2Array, s: float) -> PackedVector2Array:
	var out := PackedVector2Array()
	for p in poly:
		out.append(p * s)
	return out


func _bounds(poly: PackedVector2Array) -> Rect2:
	var lo := poly[0]
	var hi := poly[0]
	for p in poly:
		lo = Vector2(minf(lo.x, p.x), minf(lo.y, p.y))
		hi = Vector2(maxf(hi.x, p.x), maxf(hi.y, p.y))
	return Rect2(lo, hi - lo)


func _signed_area(poly: PackedVector2Array) -> float:
	var a := 0.0
	for i in poly.size():
		var p := poly[i]
		var q := poly[(i + 1) % poly.size()]
		a += p.x * q.y - q.x * p.y
	return a * 0.5


# "" when no two non-adjacent edges cross, else which pair did.
func _first_crossing(poly: PackedVector2Array) -> String:
	var n := poly.size()
	for i in n:
		var a := poly[i]
		var b := poly[(i + 1) % n]
		for j in range(i + 1, n):
			if j == (i + 1) % n or (j + 1) % n == i:
				continue  # edges sharing an endpoint always "intersect"
			if Geometry2D.segment_intersects_segment(a, b, poly[j], poly[(j + 1) % n]) != null:
				return "edges %d and %d" % [i, j]
	return ""


func _is_convex(poly: PackedVector2Array) -> bool:
	var n := poly.size()
	var sign_seen := 0
	for i in n:
		var a := poly[i]
		var b := poly[(i + 1) % n]
		var c := poly[(i + 2) % n]
		var cross := (b - a).cross(c - b)
		if absf(cross) < 1e-6:
			continue  # collinear run; the tracer emits axis-aligned steps
		var s := int(signf(cross))
		if sign_seen == 0:
			sign_seen = s
		elif s != sign_seen:
			return false
	return true
