class_name MenuShowcaseCache
extends Resource
# Docs: features/menu-showcase.md — update in the same change as this file.
# Tests: tests/headless/test_menu_showcase_cache.gd — extend in the same change.
#
# A CI/build-time snapshot of everything in MenuShowcase._build() that is CHEAP
# to cache: the track shape (pieces) and the shared bake dictionaries
# (road_heights/road_blend/track_weights/track_surface/cliff_offsets), plus the
# foliage scatter points. See features/menu-showcase.md's "Build performance"
# section for the measured before/after.
#
# DELIBERATELY DOES NOT CACHE PER-CHUNK DATA (heights/prebaked lod_meshes/coarse
# classification) — that WAS tried (see todo/menu-background-showcase.md's
# "CI-baked chunk-data store" follow-up) and measured, not assumed: it produced a
# 59 MB file that made the build SLOWER (3.6s vs 5.8s live) because
# deserialising hundreds of prebaked Mesh resources back off disk costs nearly as
# much as building them costs live. That result also confirms the ORIGINAL
# per-phase timing measurement (chunk spawning was 1% of total build time, never
# the bottleneck) — caching the cheap-to-compute, expensive-to-STORE part was
# always going to be a bad trade once actually measured.
#
# Generated by tools/generate_menu_showcase_cache.gd (invoked via
# cache_menu_showcase.sh), committed to res://data/menu_showcase_cache.res —
# same "committed lockfile, regenerated by a headless tool, missing/stale falls
# back to live with no error" shape as TrackCache/data/track_cache.json, just a
# binary Resource rather than JSON — this one holds real Dictionary/Vector2
# values TrackCache's JSON format would need extra encoding for, and a binary
# Resource holds them natively.

const CACHE_PATH := "res://data/menu_showcase_cache.res"
# Bump when TerrainManager's chunk-data shape changes (a field added/removed/
# renamed on what compute_chunk_data/cache_chunk produces), or when MenuShowcase's
# own generation constants (SHOWCASE_SEED/TURN_COUNT/STRAIGHTNESS) change in a way
# that isn't already covered by the fingerprints below. Mirrors
# TrackCache.CACHE_VERSION's own rule.
const CACHE_VERSION := "1"

## Fingerprint of every input that would make a cached build wrong if it changed:
## the showcase's own shape constants, the generator's shape/search constants
## (TrackGenerator.constants_fingerprint — the same one TrackCache folds in), and
## the terrain noise layers (TrackCache.terrain_fingerprint — reused directly
## rather than re-deriving the same fingerprint a second way).
@export var version_tag: String = ""

## The generated track's corner pieces — TrackGenerator.rebuild_from_pieces(pieces,
## params) reconstructs the exact same Curve2D from these with no search at all,
## the same mechanism TrackCache.lookup() uses. Stored natively (real Vector2/
## Dictionary values) rather than TrackCache's string-encoded form: that encoding
## exists only because JSON cannot hold a Vector2, and this cache is a binary
## Resource, which can.
@export var pieces: Array = []

## The five dictionaries TerrainManager.bake_track fills, baked once and shared
## across every segment at runtime (see MenuShowcase._share_baked_fields) — cached
## here so NONE of the six segments need to bake at all.
@export var road_heights: Dictionary = {}
@export var road_blend: Dictionary = {}
@export var track_weights: Dictionary = {}
@export var track_surface: Dictionary = {}
@export var cliff_offsets: Dictionary = {}

## The whole-track scatter, cached directly as points rather than re-derived from
## `pieces` — skips TreeScatter.scatter's own grid search entirely.
@export var tree_points: PackedVector2Array = PackedVector2Array()
@export var bush_points: PackedVector2Array = PackedVector2Array()


static func version_tag_for(cfg: GameConfig) -> String:
	return "%s:%s:%s" % [
		CACHE_VERSION,
		TrackGenerator.constants_fingerprint(),
		TrackCache.terrain_fingerprint(cfg),
	]


## Pure validity check, split out from load_if_valid so it's testable without
## touching disk: a cache is usable only if its version_tag matches the CURRENT
## generator/terrain constants — a stale cache (built before a shape-affecting
## change) must be treated exactly like a missing one, never as a silent
## correctness bug.
static func is_valid(cache: MenuShowcaseCache, cfg: GameConfig) -> bool:
	return cache != null and cache.version_tag == version_tag_for(cfg)


## Loads the committed cache and returns it only if the file exists AND
## is_valid() agrees. Returns null on any miss.
static func load_if_valid(cfg: GameConfig) -> MenuShowcaseCache:
	if not FileAccess.file_exists(CACHE_PATH):
		return null
	var cache := load(CACHE_PATH) as MenuShowcaseCache
	return cache if is_valid(cache, cfg) else null
